name: "✨ New feature"
description: Propose a new capability.
title: "[Feature] <short summary>"
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user problem will this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Outline the solution and user flow.
      placeholder: Describe API, UI, or behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: scope
    attributes:
      label: Scope / Out of Scope
      placeholder: What will be included vs. explicitly not included.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: This is not a duplicate of an existing feature request.
          required: true
